# -*- coding: utf-8 -*-
"""train_models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fo6W4zzmCirepAvmn0qD_xgkzjCJ1fm
"""

# ==============================================================================
# File: src/ml/train_models.py
# Description: Main script to orchestrate the training of ML models.
# ==============================================================================
import yaml
from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.ml.classification import RandomForestClassifier

from feature_engineering import FeatureEngineer
from model_evaluator import ModelEvaluator

def load_config(path):
    with open(path, 'r') as f:
        return yaml.safe_load(f)

def initialize_spark_session(spark_config, mongo_config):
    mongo_uri = mongo_config['uri']
    mongo_db = mongo_config['database']

    return SparkSession \
        .builder \
        .appName(f"{spark_config['app_name']}-ML-Training") \
        .config("spark.jars.packages", ",".join(spark_config['packages'])) \
        .config("spark.mongodb.input.uri", f"{mongo_uri}{mongo_db}.{mongo_config['collections']['telemetry']}") \
        .getOrCreate()