# -*- coding: utf-8 -*-
"""storage/data_schema.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUVFSqWsgBRzRvFA4NPN-wybxqMYT4y7
"""

# ==============================================================================
# File: storage/data_schema.py
# Description: Defines the document structure for collections in MongoDB.
#              This file is for documentation and clarity.
# ==============================================================================

# --- Telemetry Collection Schema ---
# Stores the raw and processed sensor data from each race session.

telemetry_document_example = {
    "_id": "ObjectId('...')",
    "session_id": "race_session_1668423600",
    "lap_id": "lap_3",
    "timestamp": "ISODate('2025-11-14T12:00:05.123Z')",
    "sensors": {
        "accelerometer": {
            "x": 1.25,
            "y": -0.5,
            "z": 9.81
        },
        "gps": {
            "lat": 40.4240,
            "lon": -86.9215,
            "speed": 75.5
        },
        "temperature": {
            "engine": 96.2,
            "brake_fl": 480.1,
            "brake_fr": 475.8
        },
        "tire_pressure": {
            "fl": 17.8,
            "fr": 18.1,
            "rl": 18.9,
            "rr": 19.0
        },
        "engine": {
            "rpm": 5200
        }
    }
}


# --- Alerts Collection Schema ---
# Stores alerts generated by the real-time streaming analytics job.

alert_document_example = {
    "_id": "ObjectId('...')",
    "timestamp": "ISODate('2025-11-14T12:01:15.456Z')",
    "alert_type": "Brake Temperature Warning",
    "message": "Front-left brake temperature critical: 550.7°C",
    "priority": "High",
    "session_id": "race_session_1668423600", # Optional: for context
    "lap_id": "lap_4" # Optional: for context
}


# --- Analytics Results Collection Schema ---
# Stores results from post-race batch analytics jobs.
# Example: Lap time summary.

lap_summary_result_example = {
    "_id": "ObjectId('...')",
    "session_id": "race_session_1668423600",
    "lap_id": "lap_3",
    "lap_time_seconds": 92.45,
    "avg_speed_kmh": 72.8,
    "max_engine_temp": 98.5
}